version: "3.7"

services:
  fluentd-timescaledb:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "${PWD}/fluentd/in_docker.conf:/fluentd/etc/fluent.conf"
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"

  timescaledb:
    image: timescale/timescaledb:latest-pg11
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - "${PWD}/docker-entrypoint-initdb.d/50_init-timescaledb-example.sh:/docker-entrypoint-initdb.d/50_init-timescaledb-example.sh"
